extends SceneTree

const RULES := preload("res://scripts/progression/training_minigame_rules.gd")

func _init() -> void:
	assert(RULES.options().size() == 4, "Training should offer four distinct specialties.")
	assert(RULES.MAX_TOTAL_SCORE == 315, "The displayed maximum must match three perfect rounds plus capped streak bonuses.")
	assert(RULES.score_round(true, 500) == 100, "Fast correct reactions should earn full points.")
	assert(RULES.score_round(true, 1200) == 70, "Slower correct reactions should receive partial points.")
	assert(RULES.score_round(false, 100) == 0, "Incorrect reactions should not earn points.")
	assert(RULES.grade(300) == "S" and RULES.grade(269) == "A", "Grade boundaries should be stable.")
	assert(RULES.grade(224) == "B" and RULES.grade(164) == "C", "Lower grade boundaries should be stable.")
	var herbs := RULES.outcome("herbalism", 280)
	assert(herbs.grade == "S" and herbs.specialty_gain == 3 and int(herbs.herbs) == 3, "Excellent herb gathering should yield specialty growth and three herb materials.")
	var mining := RULES.outcome("mining", 180)
	assert(mining.grade == "B" and mining.silver == 5 and mining.ore == 1, "Mining currency and ore output should scale with the grade.")
	assert(RULES.outcome("invalid", 300).is_empty(), "Unknown specialties must be rejected.")
	var sword := RULES.challenge("swordsmanship", "up", "right")
	assert(sword.targets == ["up", "right"], "Sword training should require an ordered two-step combo.")
	var herbs_challenge := RULES.challenge("herbalism", "left")
	assert(herbs_challenge.targets == ["right"], "Herbalism should ask players to infer the opposite root direction.")
	var advanced_sword := RULES.challenge("swordsmanship", "up", "right", true)
	assert(advanced_sword.targets == ["up", "right", "left"] and advanced_sword.advanced, "Advanced sword training should require a three-technique sequence.")
	var advanced_blade := RULES.challenge("bladesmanship", "left", "", true)
	assert(advanced_blade.targets == ["right"] and advanced_blade.ideal_ms == 1400, "Advanced blade training should telegraph a delayed counter-cut.")
	var advanced_herbs := RULES.challenge("herbalism", "left", "up", true)
	assert(advanced_herbs.targets == ["right", "down"], "Advanced herbalism should require two inferred root directions in order.")
	var advanced_mining := RULES.challenge("mining", "down", "", true)
	assert(advanced_mining.targets == ["down"] and advanced_mining.ideal_ms == 800, "Advanced mining should introduce a short echo timing window.")
	assert(RULES.score_challenge("bladesmanship", true, 1000) == 100, "Blade training should reward its centered charge window.")
	assert(RULES.score_challenge("bladesmanship", true, 200) == 55, "Swinging too early should reduce blade training score.")
	assert(RULES.score_challenge("mining", true, 1200) == 100, "Mining should reward striking on the resonance beat.")
	assert(RULES.timing_feedback("mining", 500, true) == "过早", "Timing feedback should explain an early mining strike.")
	var opening := RULES.evaluate_challenge("swordsmanship", true, 900, 0)
	assert(opening.score == 100 and opening.streak == 1 and opening.combo_bonus == 0 and opening.quality == "perfect", "The first perfect round should start a streak without a bonus.")
	var chained := RULES.evaluate_challenge("swordsmanship", true, 1500, 1)
	assert(chained.base_score == 85 and chained.combo_bonus == 5 and chained.score == 90 and chained.streak == 2, "Consecutive great rounds should earn a visible combo bonus.")
	var capped := RULES.evaluate_challenge("mining", true, 1200, 5)
	assert(capped.score == 110 and capped.combo_bonus == 10, "Combo bonuses should be capped to protect progression balance.")
	var broken := RULES.evaluate_challenge("herbalism", false, 500, 2)
	assert(broken.score == 0 and broken.streak == 0 and broken.quality == "miss", "A miss should break the performance streak.")
	var advanced_timing := RULES.evaluate_challenge("bladesmanship", true, 1400, 0, advanced_blade)
	assert(advanced_timing.score == 100 and advanced_timing.feedback == "正中时机", "Variant scoring must use the counter-cut's own timing window.")
	var advanced_sequence := RULES.evaluate_challenge("swordsmanship", true, 1700, 0, advanced_sword)
	assert(advanced_sequence.score == 100, "Longer advanced sequences need a fair expanded reaction window.")
	print("Training minigame rule tests passed.")
	quit()
