extends SceneTree

const RULES := preload("res://scripts/progression/training_minigame_rules.gd")

func _init() -> void:
	assert(RULES.options().size() == 4, "Training should offer four distinct specialties.")
	assert(RULES.weekly_focus(1) == "swordsmanship" and RULES.weekly_focus(4) == "mining" and RULES.weekly_focus(5) == "swordsmanship", "Weekly training focus should rotate deterministically across all disciplines.")
	assert(RULES.discipline_short_name("herbalism") == "采药", "Weekly-focus labels should reuse the shipping discipline names.")
	assert(RULES.specialty_rank_name(0) == "初学" and RULES.specialty_rank_name(3) == "熟手", "Early specialty thresholds should have stable names.")
	assert(RULES.specialty_rank_name(6) == "精通" and RULES.specialty_rank_name(10) == "大成", "Advanced specialty thresholds should have stable names.")
	assert(RULES.next_specialty_level(5) == 6 and RULES.next_specialty_level(10) == -1, "Specialty progress should expose the next threshold and cap cleanly.")
	assert(RULES.gathering_bonus(5) == 0 and RULES.gathering_bonus(6) == 1 and RULES.gathering_bonus(10) == 2, "Gathering yield bonuses should unlock only at mastery milestones.")
	assert(RULES.cloud_qi_cost(9) == 8 and RULES.cloud_qi_cost(10) == 6, "Sword mastery should reduce Flowing Cloud Sword's qi cost only at level ten.")
	assert(RULES.attack_exposure_gain(9) == 1 and RULES.attack_exposure_gain(10) == 2, "Blade mastery should double normal-attack exposure at level ten.")
	assert(RULES.medicine_mastery_bonus(10) == 5 and RULES.craft_ore_discount(10) == 3, "Gathering mastery should expose stable medicine and forging perks.")
	var ranked_options := RULES.options({"week": 2, "swordsmanship": 3, "mining": 10})
	assert("熟手 3级" in str(ranked_options[0][1]) and "已达大成" in str(ranked_options[3][1]), "Training choices should explain current rank and next milestone.")
	assert("本周专精" not in str(ranked_options[0][1]) and "本周专精 · 额外修为 +3" in str(ranked_options[1][1]), "Only the rotating weekly focus should advertise its cultivation bonus.")
	assert(RULES.MAX_TOTAL_SCORE == 315, "The displayed maximum must match three perfect rounds plus capped streak bonuses.")
	assert(RULES.score_round(true, 500) == 100, "Fast correct reactions should earn full points.")
	assert(RULES.score_round(true, 1200) == 70, "Slower correct reactions should receive partial points.")
	assert(RULES.score_round(false, 100) == 0, "Incorrect reactions should not earn points.")
	assert(RULES.grade(300) == "S" and RULES.grade(269) == "A", "Grade boundaries should be stable.")
	assert(RULES.grade(224) == "B" and RULES.grade(164) == "C", "Lower grade boundaries should be stable.")
	var herbs := RULES.outcome("herbalism", 280)
	assert(herbs.grade == "S" and herbs.specialty_gain == 3 and int(herbs.herbs) == 3, "Excellent herb gathering should yield specialty growth and three herb materials.")
	var mining := RULES.outcome("mining", 180)
	assert(mining.grade == "B" and mining.silver == 5 and mining.ore == 1, "Mining currency and ore output should scale with the grade.")
	assert(RULES.outcome("invalid", 300).is_empty(), "Unknown specialties must be rejected.")
	var focus_reward := RULES.outcome("swordsmanship", 180)
	focus_reward.weekly_focus_bonus = 3
	focus_reward.xp = int(focus_reward.xp) + 3
	assert("本周专精 +3修为" in RULES.reward_text(focus_reward), "Training rewards should make the weekly bonus explicit.")
	var records := RULES.empty_records()
	var first_record := RULES.record_attempt(records, "swordsmanship", 315, 3)
	assert(first_record.new_best and first_record.best_score == 315 and first_record.best_grade == "S" and first_record.attempts == 1, "A first training attempt should establish an exact personal best up to the combo maximum.")
	var lower_record := RULES.record_attempt(records, "swordsmanship", 200, 1)
	assert(not lower_record.new_best and lower_record.best_score == 315 and lower_record.best_streak == 3 and lower_record.attempts == 2, "A lower repeat should increment attempts without replacing stronger records.")
	var repaired_records := RULES.normalize_records({"swordsmanship": {"best_score": 999, "best_streak": -4, "attempts": -2}, "invalid": {"best_score": 100}})
	assert(repaired_records.size() == 4 and repaired_records.swordsmanship.best_score == 315 and repaired_records.swordsmanship.attempts == 0, "Record migration should clamp damaged values and discard unknown disciplines.")
	assert("剑 S·315（2次）" in RULES.records_text(records) and "刀 —·0（0次）" in RULES.records_text(records), "The character summary should distinguish established and untouched records.")
	var sword := RULES.challenge("swordsmanship", "up", "right")
	assert(sword.targets == ["up", "right"], "Sword training should require an ordered two-step combo.")
	var herbs_challenge := RULES.challenge("herbalism", "left")
	assert(herbs_challenge.targets == ["right"], "Herbalism should ask players to infer the opposite root direction.")
	var advanced_sword := RULES.challenge("swordsmanship", "up", "right", true)
	assert(advanced_sword.targets == ["up", "right", "left"] and advanced_sword.advanced, "Advanced sword training should require a three-technique sequence.")
	var advanced_blade := RULES.challenge("bladesmanship", "left", "", true)
	assert(advanced_blade.targets == ["right"] and advanced_blade.ideal_ms == 1400, "Advanced blade training should telegraph a delayed counter-cut.")
	var advanced_herbs := RULES.challenge("herbalism", "left", "up", true)
	assert(advanced_herbs.targets == ["right", "down"], "Advanced herbalism should require two inferred root directions in order.")
	var advanced_mining := RULES.challenge("mining", "down", "", true)
	assert(advanced_mining.targets == ["down"] and advanced_mining.ideal_ms == 800, "Advanced mining should introduce a short echo timing window.")
	assert(RULES.score_challenge("bladesmanship", true, 1000) == 100, "Blade training should reward its centered charge window.")
	assert(RULES.score_challenge("bladesmanship", true, 200) == 55, "Swinging too early should reduce blade training score.")
	assert(RULES.score_challenge("mining", true, 1200) == 100, "Mining should reward striking on the resonance beat.")
	assert(RULES.timing_feedback("mining", 500, true) == "过早", "Timing feedback should explain an early mining strike.")
	var opening := RULES.evaluate_challenge("swordsmanship", true, 900, 0)
	assert(opening.score == 100 and opening.streak == 1 and opening.combo_bonus == 0 and opening.quality == "perfect", "The first perfect round should start a streak without a bonus.")
	var chained := RULES.evaluate_challenge("swordsmanship", true, 1500, 1)
	assert(chained.base_score == 85 and chained.combo_bonus == 5 and chained.score == 90 and chained.streak == 2, "Consecutive great rounds should earn a visible combo bonus.")
	var capped := RULES.evaluate_challenge("mining", true, 1200, 5)
	assert(capped.score == 110 and capped.combo_bonus == 10, "Combo bonuses should be capped to protect progression balance.")
	var broken := RULES.evaluate_challenge("herbalism", false, 500, 2)
	assert(broken.score == 0 and broken.streak == 0 and broken.quality == "miss", "A miss should break the performance streak.")
	var advanced_timing := RULES.evaluate_challenge("bladesmanship", true, 1400, 0, advanced_blade)
	assert(advanced_timing.score == 100 and advanced_timing.feedback == "正中时机", "Variant scoring must use the counter-cut's own timing window.")
	var advanced_sequence := RULES.evaluate_challenge("swordsmanship", true, 1700, 0, advanced_sword)
	assert(advanced_sequence.score == 100, "Longer advanced sequences need a fair expanded reaction window.")
	print("Training minigame rule tests passed.")
	quit()
