extends SceneTree

const RULES := preload("res://scripts/progression/training_minigame_rules.gd")

func _init() -> void:
	assert(RULES.options().size() == 4, "Training should offer four distinct specialties.")
	assert(RULES.score_round(true, 500) == 100, "Fast correct reactions should earn full points.")
	assert(RULES.score_round(true, 1200) == 70, "Slower correct reactions should receive partial points.")
	assert(RULES.score_round(false, 100) == 0, "Incorrect reactions should not earn points.")
	assert(RULES.grade(300) == "S" and RULES.grade(269) == "A", "Grade boundaries should be stable.")
	assert(RULES.grade(224) == "B" and RULES.grade(164) == "C", "Lower grade boundaries should be stable.")
	var herbs := RULES.outcome("herbalism", 280)
	assert(herbs.grade == "S" and herbs.specialty_gain == 3 and herbs.item == "上品药材", "Excellent herb gathering should yield specialty growth and premium herbs.")
	var mining := RULES.outcome("mining", 180)
	assert(mining.grade == "B" and mining.silver == 5, "Mining output should scale with the grade.")
	assert(RULES.outcome("invalid", 300).is_empty(), "Unknown specialties must be rejected.")
	var sword := RULES.challenge("swordsmanship", "up", "right")
	assert(sword.targets == ["up", "right"], "Sword training should require an ordered two-step combo.")
	var herbs_challenge := RULES.challenge("herbalism", "left")
	assert(herbs_challenge.targets == ["right"], "Herbalism should ask players to infer the opposite root direction.")
	assert(RULES.score_challenge("bladesmanship", true, 1000) == 100, "Blade training should reward its centered charge window.")
	assert(RULES.score_challenge("bladesmanship", true, 200) == 55, "Swinging too early should reduce blade training score.")
	assert(RULES.score_challenge("mining", true, 1200) == 100, "Mining should reward striking on the resonance beat.")
	assert(RULES.timing_feedback("mining", 500, true) == "过早", "Timing feedback should explain an early mining strike.")
	print("Training minigame rule tests passed.")
	quit()
